In [1]:
import numpy as np
import pandas as pd

In [2]:
df_chi = pd.read_csv('chi-test.csv')

In [3]:
contigency_table = pd.crosstab(df_chi['Gender'],df_chi['Shopping?'])

In [4]:
contigency_table

Shopping?  No  Yes
Gender            
Female      2    3
Male        2    2

In [5]:
Observed_Values = contigency_table.values

In [7]:
type(Observed_Values)

numpy.ndarray

In [13]:
Observed_Values

array([[2, 3],
       [2, 2]])

In [8]:
from scipy.stats import chi2_contingency

In [9]:
b = chi2_contingency(contigency_table)

In [10]:
b

(0.1406249999999999,
 0.7076604666545525,
 1,
 array([[2.22222222, 2.77777778],
        [1.77777778, 2.22222222]]))

In [11]:
Expected_Values = b[3]

In [12]:
Expected_Values

array([[2.22222222, 2.77777778],
       [1.77777778, 2.22222222]])

In [14]:
Degree_of_Freedom = b[2]

In [16]:
Chi_Square_Statistic_Value = b[0]

In [18]:
alpha = 0.05

In [19]:
from scipy.stats import chi2

In [21]:
critical_value= chi2.ppf(q=1-alpha,df=1)

In [22]:
critical_value

3.841458820694124

In [23]:
p_value = 1 - chi2.cdf(x=Chi_Square_Statistic_Value,df=1)

In [24]:
p_value

0.7076604666545525

In [25]:
print ("Method 1 - Using Chi-Square Statistic and Critical Value")

if Chi_Square_Statistic_Value >= critical_value:
    print("Reject H0, There is a relationship between gender and shopping")
else:
    print("Accept H0, There is no relationship between gender and shopping")

Method 1 - Using Chi-Square Statistic and Critical Value
Accept H0, There is no relationship between gender and shopping


In [26]:
print ("Method 2 - Using p-value and the alpha value")

if p_value <= alpha:
    print("Reject H0, There is a relationship between gender and shopping")
else:
    print("Accept H0, There is no relationship between gender and shopping")

Method 2 - Using p-value and the alpha value
Accept H0, There is no relationship between gender and shopping
